Escalation:
    path:     /escalation
    defaults: { _controller: AppBundle:Escalation:escalation }

EscalationFrontEnd:
    path:     /escalationFrontEnd
    defaults: { _controller: AppBundle:Escalation:escalationFrontEnd }
