# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    api.zendesk:
      class: AppBundle\Utility\ZendeskApi
      arguments:
        - '%api_user%'
        - '%api_pass%'
