# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    api.zendesk:
        class: AppBundle\Utility\ZendeskApi
        arguments:
            - '%zendesk.api_user%'
            - '%zendesk.api_pass%'
    api.slack:
        class: AppBundle\Utility\SlackApi
        arguments:
            - '%slack.api_token%'
            - '%slack.api_username%'
            - '%slack.api_icon_emoji%'
